blank_issues_enabled: false
contact_links:
  - name: Duvidas gerais
    url: https://github.com/inovaflowtecsys-afk/juliananardaci/discussions
    about: Use discussions para perguntas e conversas gerais
